### ISSUE TITLE
Unable to compile the project

### ISSUE THREAD

**Issue by urdsheir** [ahocevar/openlayers-geopackage-demo#11]
Hi,
I have tried to install your demo but unable to do so. There were compilation errors. I have attached the log. Any help would be much appreciated. Thanks
[2021-06-14T21_18_16_555Z-debug.log](https://github.com/ahocevar/openlayers-geopackage-demo/files/6653354/2021-06-14T21_18_16_555Z-debug.log)

**Comment by ahocevar** [comment]
Can you pull the latest and try again please? I just pushed an update with version updates of the dependencies.

**Comment by urdsheir** [comment]
Thanks for your help. We were able to compile using node-v13 but not with the node-v15. @ngageoint/geopackage
has a depdency over Canvas package which was creating problem.
